### ISSUE TITLE
wo host?

### ISSUE THREAD

**Issue by TitanProgrammer4480** [Kerzinator24/Minecraft-Inventory-Edit#1]
wo ist das gehostet? hab den link verloren und kann nicht discord öffnen

**Comment by TitanProgrammer4480** [comment]
@Kerzinator24 hallo?

**Comment by Kerzinator24** [comment]
@TitanProgrammer4480 hier https://codepen.io/Kerzinator-24/full/yLmPWro

**Comment by TitanProgrammer4480** [comment]
@Kerzinator24 für welchen zweck soll das sein?

**Comment by TitanProgrammer4480** [comment]
das inventar

**Comment by TitanProgrammer4480** [comment]
gibt es eine list von den name von mc-items

**Comment by TitanProgrammer4480** [comment]
@Kerzinator24 der export funktioniert überhaupt nicht, kann items nur im 1. feld anzeigen, kann das feld nur anzeigen wenn ich auf sourcecode zeigen gehen. All in all das teil hat mehr bugs als meine gesmaten projekte zusammen

**Comment by Kerzinator24** [comment]
Kannst du mit der Problembeschreibung bitte genauer sein? Bei mir funktioniert alles. Verwendest du die Website auf einem Handy?

**Comment by TitanProgrammer4480** [comment]
auf ipad
